name: infinity-clean
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - comm=0.2.2=pyhd8ed1ab_1
  - debugpy=1.8.11=py310h6a678d5_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.37.0=pyh8f84b5b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=7.3.4=pyhd8ed1ab_0
  - jupyter_core=5.8.1=pyh31011fe_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.0.16=h5eee18b_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.1=pyhc872135_2
  - platformdirs=4.3.8=pyhe01879c_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - python=3.10.16=he870216_1
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python_abi=3.10=2_cp310
  - pyzmq=26.2.0=py310h6a678d5_0
  - readline=8.2=h5eee18b_0
  - setuptools=78.1.1=py310h06a4308_0
  - six=1.17.0=pyhd8ed1ab_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.14=h39e8969_0
  - tornado=6.1=py310h5764c6d_3
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.14.0=pyhe01879c_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=py310h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_1
  - pip:
    - aiofiles==24.1.0
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.11.18
    - aiosignal==1.3.2
    - annotated-types==0.7.0
    - antlr4-python3-runtime==4.9.3
    - anyio==3.7.1
    - astroid==3.3.11
    - async-timeout==5.0.1
    - attrs==25.3.0
    - brotli==1.1.0
    - certifi==2025.4.26
    - charset-normalizer==3.4.2
    - click==8.2.0
    - clip-score==0.2.1
    - colorama==0.4.6
    - contourpy==1.3.2
    - cycler==0.12.1
    - decord==0.6.0
    - dill==0.4.0
    - docker-pycreds==0.4.0
    - docstring-parser==0.16
    - easydict==1.13
    - einops==0.8.1
    - fastapi==0.116.1
    - ffmpy==0.6.0
    - filelock==3.13.1
    - flash-attn==2.7.4.post1
    - fonttools==4.58.0
    - frozenlist==1.6.0
    - fsspec==2024.6.1
    - ftfy==6.3.1
    - gitdb==4.0.12
    - gitpython==3.1.44
    - gputil==1.4.0
    - gradio==5.38.0
    - gradio-client==1.11.0
    - groovy==0.1.2
    - h11==0.16.0
    - httpcore==1.0.9
    - httpx==0.28.1
    - huggingface-hub==0.31.2
    - idna==3.10
    - imageio==2.37.0
    - isort==6.0.1
    - jinja2==3.1.4
    - kiwisolver==1.4.8
    - kornia==0.8.1
    - kornia-rs==0.1.9
    - lightning-utilities==0.15.0
    - markdown-it-py==3.0.0
    - markupsafe==2.1.5
    - matplotlib==3.10.3
    - mccabe==0.7.0
    - mdurl==0.1.2
    - mpmath==1.3.0
    - multidict==6.4.3
    - mypy-extensions==1.1.0
    - networkx==3.3
    - ninja==1.11.1.4
    - numpy==2.1.2
    - nvidia-cublas-cu12==12.6.4.1
    - nvidia-cuda-cupti-cu12==12.6.80
    - nvidia-cuda-nvrtc-cu12==12.6.77
    - nvidia-cuda-runtime-cu12==12.6.77
    - nvidia-cudnn-cu12==9.5.1.17
    - nvidia-cufft-cu12==11.3.0.4
    - nvidia-curand-cu12==10.3.7.77
    - nvidia-cusolver-cu12==11.7.1.2
    - nvidia-cusparse-cu12==12.5.4.2
    - nvidia-cusparselt-cu12==0.6.3
    - nvidia-nccl-cu12==2.21.5
    - nvidia-nvjitlink-cu12==12.6.85
    - nvidia-nvtx-cu12==12.6.77
    - omegaconf==2.3.0
    - openai==0.28.1
    - opencv-python==4.11.0.86
    - orjson==3.11.0
    - pandas==2.2.3
    - pillow==11.0.0
    - propcache==0.3.1
    - protobuf==6.31.0
    - psutil==7.0.0
    - pydantic==2.11.4
    - pydantic-core==2.33.2
    - pydeps==3.0.1
    - pydub==0.25.1
    - pyparsing==3.2.3
    - python-graphviz==0.21
    - python-multipart==0.0.20
    - pytorch-fid==0.3.0
    - pytorch-lightning==2.5.2
    - pytz==2025.2
    - pyyaml==6.0.2
    - regex==2024.11.6
    - requests==2.32.3
    - rfc3986==1.5.0
    - rich==14.0.0
    - ruff==0.12.4
    - safehttpx==0.1.6
    - safetensors==0.5.3
    - scipy==1.15.3
    - seaborn==0.13.2
    - semantic-version==2.10.0
    - sentry-sdk==2.28.0
    - setproctitle==1.3.6
    - shellingham==1.5.4
    - smmap==5.0.2
    - sniffio==1.3.1
    - starlette==0.47.1
    - stdlib-list==0.11.1
    - sympy==1.13.1
    - timm==0.9.6
    - tokenizers==0.21.1
    - tomli==2.2.1
    - tomlkit==0.13.3
    - torch==2.6.0+cu126
    - torchaudio==2.6.0+cu126
    - torchmetrics==1.8.0
    - torchview==0.2.7
    - torchvision==0.21.0+cu126
    - tqdm==4.67.1
    - transformers==4.51.3
    - triton==3.2.0
    - typed-argument-parser==1.10.1
    - typer==0.16.0
    - typing-extensions==4.12.2
    - typing-inspect==0.9.0
    - typing-inspection==0.4.0
    - tzdata==2025.2
    - urllib3==2.4.0
    - uvicorn==0.35.0
    - wandb==0.20.1
    - websockets==15.0.1
    - yarl==1.20.0

